### ISSUE TITLE
casa6 update: Modify RegionTextParser to handle long CRTF polygon definition

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-casacore#7]
Updating the casa6 submodule to master, along with its casacore submodule update, revealed a std::regex issue when importing a CRTF polygon region with as many as 6000 points.  This import causes a seg fault in the std::regex code.  See Slack backend channel for test image **gaussian.fits** and test CRTF file **polygon_6000,crtf** with the poly file line > 150,000 characters.

The fix would involve modifying casa::RegionTextParser in the imageanalysis code to avoid using std::regex_search to match the entire polygon region definition for validation (via casacore::String::contains and casacore::String::through with casacore::Regex argument).  Instead, the definition can be validated point by point.

This change must be made in casa code, with collaboration/approval from Dave Mehringer.  After it is merged into master, the **update_casa6_master** branch needs to be updated to this commit, tested, and merged to close this issue.

**Comment by kswang1029** [comment]
confirmed with https://github.com/CARTAvis/carta-casacore/pull/17, long polygon CRTF region can be loaded in CARTA successfully.
